/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import Clases.CallCenter;
import Clases.Empleado;
import Modelo.modelEmpleado;
import java.util.ArrayList;
import java.util.LinkedList;
import javax.swing.DefaultListModel;
import javax.swing.DefaultListSelectionModel;
import javax.swing.JOptionPane;
import java.util.HashMap;


/**
 *
 * @author HOME
 */
public class frmPrincipal extends javax.swing.JFrame {
     LinkedList<Empleado> empleadoLista = new LinkedList<> ();
    
     CallCenter liquidacion =  new CallCenter();
     modelEmpleado mdEmpleado = new modelEmpleado();
     Empleado empleado;
     
    public frmPrincipal() {
        initComponents();
        this.empleadoLista = mdEmpleado.listaEmpleado();
        this.listaEmpleado();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPasswordField1 = new javax.swing.JPasswordField();
        jPanel10 = new javax.swing.JPanel();
        TablepaneGroup = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jlabeCodigo1 = new javax.swing.JLabel();
        jTextCodigoidEdicion = new javax.swing.JTextField();
        bttConsutaEdicion = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jPaInfoEmpleado2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jTexNombreEditar = new javax.swing.JTextField();
        jLabApellido2 = new javax.swing.JLabel();
        jTextApellidoEdit = new javax.swing.JTextField();
        jPanelDatosSalario2 = new javax.swing.JPanel();
        jLabelInfoNomina2 = new javax.swing.JLabel();
        jLabelSalario2 = new javax.swing.JLabel();
        jLabelHorasExtras2 = new javax.swing.JLabel();
        jCheckBoxAuxilioTransporteEdit = new javax.swing.JCheckBox();
        jTextSalarioEdit = new javax.swing.JTextField();
        jTexHorasExtraEdit = new javax.swing.JTextField();
        jButtoGuardarCambiosEdicion = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPaInfoEmpleado1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTexNombreEmpleado1 = new javax.swing.JTextField();
        jLabApellido1 = new javax.swing.JLabel();
        jTextApellidoEmpleado1 = new javax.swing.JTextField();
        jPanelDatosSalario1 = new javax.swing.JPanel();
        jLabelInfoNomina1 = new javax.swing.JLabel();
        jLabelSalario1 = new javax.swing.JLabel();
        jLabelHorasExtras1 = new javax.swing.JLabel();
        jCheckBoxAuxilioTransporteEmpleado = new javax.swing.JCheckBox();
        jTextSalario1 = new javax.swing.JTextField();
        jTexHorasExtrasEmpleado1 = new javax.swing.JTextField();
        jButtonGuardarEmpleado = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jlabeCodigo = new javax.swing.JLabel();
        jTextCodigoid = new javax.swing.JTextField();
        bttConsulEmpleado = new javax.swing.JButton();
        jPaInfoEmpleado = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTexNombre = new javax.swing.JTextField();
        jLabApellido = new javax.swing.JLabel();
        jTextApellido = new javax.swing.JTextField();
        jPanelDatosSalario = new javax.swing.JPanel();
        jLabelInfoNomina = new javax.swing.JLabel();
        jLabelSalario = new javax.swing.JLabel();
        jLabelHorasExtras = new javax.swing.JLabel();
        jCheckBoxAuxilioTransporte = new javax.swing.JCheckBox();
        jTextSalario = new javax.swing.JTextField();
        jTexHorasExtras = new javax.swing.JTextField();
        jButtonGenerarNOMINA = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLTotalNomina = new javax.swing.JLabel();
        jTexNomina = new javax.swing.JTextField();
        jLTotalPrestaciones = new javax.swing.JLabel();
        jTextTotalPrestaciones = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jTexCodigoEliminar = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jButEliminarEmpleado = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jlistEmpleado = new javax.swing.JList<>();
        jPanel16 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButtonProsesoMasivo = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1NominaMasiva = new javax.swing.JList<>();

        jPasswordField1.setText("jPasswordField1");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel5.setText("Rejistrar Empleado");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addComponent(jLabel5)
                .addContainerGap(166, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(28, 28, 28))
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel6.setText("Consultar Empleado");

        jlabeCodigo1.setText("Codigo");

        bttConsutaEdicion.setText("Consultar Empleado");
        bttConsutaEdicion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttConsutaEdicionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel8Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jlabeCodigo1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextCodigoidEdicion, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel8Layout.createSequentialGroup()
                            .addGap(144, 144, 144)
                            .addComponent(bttConsutaEdicion))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlabeCodigo1)
                    .addComponent(jTextCodigoidEdicion, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bttConsutaEdicion)
                .addGap(14, 14, 14))
        );

        jPaInfoEmpleado2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel8.setText("Nombre");

        jLabApellido2.setText("Apellido");

        javax.swing.GroupLayout jPaInfoEmpleado2Layout = new javax.swing.GroupLayout(jPaInfoEmpleado2);
        jPaInfoEmpleado2.setLayout(jPaInfoEmpleado2Layout);
        jPaInfoEmpleado2Layout.setHorizontalGroup(
            jPaInfoEmpleado2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPaInfoEmpleado2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPaInfoEmpleado2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPaInfoEmpleado2Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabApellido2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPaInfoEmpleado2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTexNombreEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPaInfoEmpleado2Layout.createSequentialGroup()
                .addComponent(jTextApellidoEdit)
                .addGap(6, 6, 6))
        );
        jPaInfoEmpleado2Layout.setVerticalGroup(
            jPaInfoEmpleado2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPaInfoEmpleado2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTexNombreEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabApellido2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextApellidoEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanelDatosSalario2.setBackground(new java.awt.Color(204, 204, 255));

        jLabelInfoNomina2.setBackground(new java.awt.Color(0, 0, 0));
        jLabelInfoNomina2.setText("Informacion Nomina Empleado");

        jLabelSalario2.setText("Salario");

        jLabelHorasExtras2.setText("Valor Horas Extras ");

        jCheckBoxAuxilioTransporteEdit.setText("Auxilio Transporte");

        jTexHorasExtraEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTexHorasExtraEditActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelDatosSalario2Layout = new javax.swing.GroupLayout(jPanelDatosSalario2);
        jPanelDatosSalario2.setLayout(jPanelDatosSalario2Layout);
        jPanelDatosSalario2Layout.setHorizontalGroup(
            jPanelDatosSalario2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosSalario2Layout.createSequentialGroup()
                .addGroup(jPanelDatosSalario2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDatosSalario2Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabelInfoNomina2))
                    .addGroup(jPanelDatosSalario2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanelDatosSalario2Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabelHorasExtras2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTexHorasExtraEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelDatosSalario2Layout.createSequentialGroup()
                            .addGap(15, 15, 15)
                            .addGroup(jPanelDatosSalario2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jCheckBoxAuxilioTransporteEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanelDatosSalario2Layout.createSequentialGroup()
                                    .addComponent(jLabelSalario2)
                                    .addGap(56, 56, 56)
                                    .addComponent(jTextSalarioEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelDatosSalario2Layout.setVerticalGroup(
            jPanelDatosSalario2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosSalario2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelInfoNomina2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDatosSalario2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelSalario2)
                    .addComponent(jTextSalarioEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDatosSalario2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelHorasExtras2)
                    .addComponent(jTexHorasExtraEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBoxAuxilioTransporteEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jButtoGuardarCambiosEdicion.setText("Guardar Cambios");
        jButtoGuardarCambiosEdicion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtoGuardarCambiosEdicionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPaInfoEmpleado2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelDatosSalario2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(jButtoGuardarCambiosEdicion, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPaInfoEmpleado2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelDatosSalario2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtoGuardarCambiosEdicion))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 409, Short.MAX_VALUE))
                    .addComponent(jPanel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(136, Short.MAX_VALUE))
        );

        TablepaneGroup.addTab("Editar Empleado", jPanel4);

        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel3.setText("Rejistrar Empleado");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addComponent(jLabel3)
                .addContainerGap(166, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(28, 28, 28))
        );

        jPaInfoEmpleado1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel4.setText("Nombre");

        jLabApellido1.setText("Apellido");

        javax.swing.GroupLayout jPaInfoEmpleado1Layout = new javax.swing.GroupLayout(jPaInfoEmpleado1);
        jPaInfoEmpleado1.setLayout(jPaInfoEmpleado1Layout);
        jPaInfoEmpleado1Layout.setHorizontalGroup(
            jPaInfoEmpleado1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPaInfoEmpleado1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPaInfoEmpleado1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPaInfoEmpleado1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabApellido1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPaInfoEmpleado1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTexNombreEmpleado1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPaInfoEmpleado1Layout.createSequentialGroup()
                .addComponent(jTextApellidoEmpleado1)
                .addGap(6, 6, 6))
        );
        jPaInfoEmpleado1Layout.setVerticalGroup(
            jPaInfoEmpleado1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPaInfoEmpleado1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTexNombreEmpleado1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabApellido1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextApellidoEmpleado1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanelDatosSalario1.setBackground(new java.awt.Color(204, 204, 255));

        jLabelInfoNomina1.setBackground(new java.awt.Color(0, 0, 0));
        jLabelInfoNomina1.setText("Informacion Nomina Empleado");

        jLabelSalario1.setText("Salario");

        jLabelHorasExtras1.setText("Valor Horas Extras ");

        jCheckBoxAuxilioTransporteEmpleado.setText("Auxilio Transporte");

        jTextSalario1.setText("0");

        jTexHorasExtrasEmpleado1.setText("0");

        javax.swing.GroupLayout jPanelDatosSalario1Layout = new javax.swing.GroupLayout(jPanelDatosSalario1);
        jPanelDatosSalario1.setLayout(jPanelDatosSalario1Layout);
        jPanelDatosSalario1Layout.setHorizontalGroup(
            jPanelDatosSalario1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosSalario1Layout.createSequentialGroup()
                .addGroup(jPanelDatosSalario1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDatosSalario1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabelInfoNomina1))
                    .addGroup(jPanelDatosSalario1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanelDatosSalario1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabelHorasExtras1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTexHorasExtrasEmpleado1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelDatosSalario1Layout.createSequentialGroup()
                            .addGap(15, 15, 15)
                            .addGroup(jPanelDatosSalario1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jCheckBoxAuxilioTransporteEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanelDatosSalario1Layout.createSequentialGroup()
                                    .addComponent(jLabelSalario1)
                                    .addGap(56, 56, 56)
                                    .addComponent(jTextSalario1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(301, Short.MAX_VALUE))
        );
        jPanelDatosSalario1Layout.setVerticalGroup(
            jPanelDatosSalario1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosSalario1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelInfoNomina1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDatosSalario1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelSalario1)
                    .addComponent(jTextSalario1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDatosSalario1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelHorasExtras1)
                    .addComponent(jTexHorasExtrasEmpleado1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBoxAuxilioTransporteEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jButtonGuardarEmpleado.setText("Guardar Empleado");
        jButtonGuardarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarEmpleadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPaInfoEmpleado1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelDatosSalario1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(jButtonGuardarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPaInfoEmpleado1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelDatosSalario1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonGuardarEmpleado))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 226, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(296, Short.MAX_VALUE))
        );

        TablepaneGroup.addTab("CreateEmpleado", jPanel1);

        jPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setText("Consultar Empleado");

        jlabeCodigo.setText("Codigo");

        bttConsulEmpleado.setText("Consultar Empleado");
        bttConsulEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttConsulEmpleadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelLayout = new javax.swing.GroupLayout(jPanel);
        jPanel.setLayout(jPanelLayout);
        jPanelLayout.setHorizontalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jlabeCodigo)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextCodigoid, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanelLayout.createSequentialGroup()
                            .addGap(144, 144, 144)
                            .addComponent(bttConsulEmpleado))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelLayout.setVerticalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlabeCodigo)
                    .addComponent(jTextCodigoid, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bttConsulEmpleado)
                .addGap(14, 14, 14))
        );

        jPaInfoEmpleado.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setText("Nombre");

        jTexNombre.setEditable(false);

        jLabApellido.setText("Apellido");

        jTextApellido.setEditable(false);

        javax.swing.GroupLayout jPaInfoEmpleadoLayout = new javax.swing.GroupLayout(jPaInfoEmpleado);
        jPaInfoEmpleado.setLayout(jPaInfoEmpleadoLayout);
        jPaInfoEmpleadoLayout.setHorizontalGroup(
            jPaInfoEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPaInfoEmpleadoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPaInfoEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPaInfoEmpleadoLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPaInfoEmpleadoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTexNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPaInfoEmpleadoLayout.createSequentialGroup()
                .addComponent(jTextApellido)
                .addGap(6, 6, 6))
        );
        jPaInfoEmpleadoLayout.setVerticalGroup(
            jPaInfoEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPaInfoEmpleadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTexNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanelDatosSalario.setBackground(new java.awt.Color(204, 204, 255));

        jLabelInfoNomina.setBackground(new java.awt.Color(0, 0, 0));
        jLabelInfoNomina.setText("Informacion Nomina Empleado");

        jLabelSalario.setText("Salario");

        jLabelHorasExtras.setText("Valor Horas Extras ");

        jCheckBoxAuxilioTransporte.setText("Auxilio Transporte");

        jTextSalario.setEditable(false);

        jTexHorasExtras.setEditable(false);

        javax.swing.GroupLayout jPanelDatosSalarioLayout = new javax.swing.GroupLayout(jPanelDatosSalario);
        jPanelDatosSalario.setLayout(jPanelDatosSalarioLayout);
        jPanelDatosSalarioLayout.setHorizontalGroup(
            jPanelDatosSalarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosSalarioLayout.createSequentialGroup()
                .addGroup(jPanelDatosSalarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDatosSalarioLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabelInfoNomina))
                    .addGroup(jPanelDatosSalarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanelDatosSalarioLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabelHorasExtras)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTexHorasExtras, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelDatosSalarioLayout.createSequentialGroup()
                            .addGap(15, 15, 15)
                            .addGroup(jPanelDatosSalarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jCheckBoxAuxilioTransporte, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanelDatosSalarioLayout.createSequentialGroup()
                                    .addComponent(jLabelSalario)
                                    .addGap(56, 56, 56)
                                    .addComponent(jTextSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(527, Short.MAX_VALUE))
        );
        jPanelDatosSalarioLayout.setVerticalGroup(
            jPanelDatosSalarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosSalarioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelInfoNomina, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDatosSalarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelSalario)
                    .addComponent(jTextSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDatosSalarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelHorasExtras)
                    .addComponent(jTexHorasExtras, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBoxAuxilioTransporte, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jButtonGenerarNOMINA.setText("Generar Nomina");
        jButtonGenerarNOMINA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGenerarNOMINAActionPerformed(evt);
            }
        });

        jLTotalNomina.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLTotalNomina.setText("Total Nomina Empleado");

        jTexNomina.setEditable(false);
        jTexNomina.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jTexNomina.setText("0");

        jLTotalPrestaciones.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLTotalPrestaciones.setText("Total Prestaciones ");

        jTextTotalPrestaciones.setEditable(false);
        jTextTotalPrestaciones.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jTextTotalPrestaciones.setText("0");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLTotalNomina))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLTotalPrestaciones)))
                .addGap(49, 49, 49)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTexNomina)
                    .addComponent(jTextTotalPrestaciones))
                .addGap(28, 28, 28))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTexNomina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLTotalNomina))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLTotalPrestaciones))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jTextTotalPrestaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jPaInfoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanelDatosSalario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(jButtonGenerarNOMINA, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPaInfoEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelDatosSalario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonGenerarNOMINA)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(130, Short.MAX_VALUE))
        );

        TablepaneGroup.addTab("liqNomia", jPanel2);

        jPanel12.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel7.setText("Eliminar Empleado");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addComponent(jLabel7)
                .addContainerGap(166, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(28, 28, 28))
        );

        jPanel14.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Codigo");

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel10.setText("Consultar Empleado");

        jButEliminarEmpleado.setText("Eliminar Empleado");
        jButEliminarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButEliminarEmpleadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(175, 175, 175)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButEliminarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(jTexCodigoEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel10)
                .addGap(44, 44, 44)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTexCodigoEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jButEliminarEmpleado)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(376, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(218, Short.MAX_VALUE))
        );

        TablepaneGroup.addTab("Eliminar", jPanel11);

        jPanel15.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel11.setText("Lista De Empleados");

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(350, Short.MAX_VALUE))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel11)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        jlistEmpleado.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Empleado 1", "Empleado 2", "Empleado 3", "Empleado 4", "Empleado 5", "Empleado 6" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jlistEmpleado);

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(244, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        TablepaneGroup.addTab("Empleados", jPanel13);

        jPanel17.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel12.setText("Año:");

        jTextField1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jTextField1.setText("2022");

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel13.setText("Mes:");

        jComboBox1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Nobiembre", "Diciembre" }));

        jButtonProsesoMasivo.setFont(new java.awt.Font("Dialog", 1, 21)); // NOI18N
        jButtonProsesoMasivo.setText("Procesar");
        jButtonProsesoMasivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProsesoMasivoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField1))
                .addGap(88, 88, 88)
                .addComponent(jButtonProsesoMasivo, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(197, Short.MAX_VALUE))
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel17Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonProsesoMasivo, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel17Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        jScrollPane2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jList1NominaMasiva.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane2.setViewportView(jList1NominaMasiva);

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 227, Short.MAX_VALUE))
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 721, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(192, Short.MAX_VALUE))
        );

        TablepaneGroup.addTab("Liquidacion Masiva Nomina ", jPanel16);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(TablepaneGroup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TablepaneGroup, javax.swing.GroupLayout.PREFERRED_SIZE, 651, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttConsulEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttConsulEmpleadoActionPerformed
 
                                                           
         /* Creamos un objeto de tipo empleado y el valor que 
           le asignamos es el objeto de model empleado 
            y una ves echo esto podemos utilizar su metodos                                                
            muy buena idea                                                
                                                           */                                                  
        empleado = mdEmpleado.consultaEmpleadoId(jTextCodigoid.getText());  
        
        if (empleado == null ){// si el empleado no existe ponemos un mensaje en pantalla
            JOptionPane.showMessageDialog(rootPane, "Empleado no Existe");
            
            /* llamamos la variable donde esta el nombre y con el set le ponemos
             en su interior el objeto empleado  luego acedemos a su nombre 
            y lo ponemos alli gracias al metodo set esto con el fin de que lo
            muestre en la pantalla grafica 
            */
            jTexNombre.setText(""); 
            jTextApellido.setText("");
            jTextSalario.setText("");
            jTexHorasExtras.setText("");
            //jCheckBoxAuxilioTransporte.setSelected(false);
            
            jTextTotalPrestaciones.setText("0");
            jTexNomina.setText("0");
            
            
        }else{
            jTexNombre.setText(empleado.getNombre()); 
            jTextApellido.setText(empleado.getApellido());
            jTextSalario.setText(String.valueOf(empleado.getSalario()));
            jTexHorasExtras.setText(String.valueOf(empleado.getHorasExtra()));
            jCheckBoxAuxilioTransporte.setSelected(empleado.isAuxilioTransporte());
            
            jTextTotalPrestaciones.setText("0");
            jTexNomina.setText("0");
        }
    }//GEN-LAST:event_bttConsulEmpleadoActionPerformed

    private void jButtonGenerarNOMINAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGenerarNOMINAActionPerformed
        // TODO add your handling code here:
        
        // traemos estos metodos porque necesitamos sus datos
        
       CallCenter liquidacion =  new CallCenter(); 
       ArrayList<Double> nomina = new ArrayList<>();
       ArrayList<Double> prestacion = new ArrayList<>();
       
       modelEmpleado modelConsulta = new modelEmpleado();
       Empleado empleado = modelConsulta.consultaEmpleadoId(jTextCodigoid.getText());
       
       System.out.println("Liquidacion Nomina ");
       nomina = liquidacion.liquidarNomiaEmp(empleado);// recibe la lista que creamos
                                                            // en las lineas anteriores
                                                            
        for (int i = 0; i < nomina.size(); i++) {
            System.out.println("total A pagar"+Math.round(nomina.get(i)));
            jTexNomina.setText(String.valueOf(Math.round(nomina.get(i))));
           
        }
        
        System.out.println("Prestaciones Sociales");
        prestacion = liquidacion.liquidarPrestacionesEmp(empleado);
        for (int i = 0; i < prestacion.size(); i++) {
            System.out.println("total a pagar"+Math.round(prestacion.get(i)));
             jTextTotalPrestaciones.setText(String.valueOf(Math.round(prestacion.get(i))));
        } 
    }//GEN-LAST:event_jButtonGenerarNOMINAActionPerformed

    private void jButtonGuardarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarEmpleadoActionPerformed
        // TODO add your handling code here

        try {
            if (jTexNombreEmpleado1.getText().equals("") || jTextApellidoEmpleado1.getText().equals("") || (Integer.valueOf(jTextSalario1.getText()) <= 0)) {
                System.out.println("Nombre:  "+jTexNombreEmpleado1.getText()+" apellido "+jTextApellido.getText()+ "  "+Integer.valueOf(jTextSalario1.getText()));
                JOptionPane.showMessageDialog(rootPane, "los Datos Nombre,Apellido,Salario , Son Obligatorios");

            } else {
                        
                if (mdEmpleado.crearEmpleado(jTexNombreEmpleado1.getText(), Integer.valueOf(jTexHorasExtrasEmpleado1.getText()), jCheckBoxAuxilioTransporteEmpleado.isSelected(), Integer.valueOf(jTextSalario1.getText()), jTextApellidoEmpleado1.getText())) {
                    
                    JOptionPane.showMessageDialog(rootPane, "Empleado Guardado Correctamente\n" + jTexNombreEmpleado1.getText() + " " + jTextApellido.getText());

                    jTexNombreEmpleado1.setText("");
                    jTextApellidoEmpleado1.setText("");
                    jTextSalario1.setText("0");
                    jTexHorasExtrasEmpleado1.setText("0");
                    jCheckBoxAuxilioTransporteEmpleado.setSelected(false);
                    actVistaempleado();

                } else {
                    JOptionPane.showMessageDialog(rootPane, "No Guardo Intente De nuevo\n" + jTexNombreEmpleado1.getText() + " " + jTextApellidoEmpleado1.getText());

                }
            }

           
        } catch (Exception e) {
             JOptionPane.showMessageDialog(rootPane, "Error: \n Error Salario y Horas Extras Son Datos Numericos ");
            //(String nombre,int horasExtra,boolean AuxilioTransp,int salario,String apellido) 
        }
    }//GEN-LAST:event_jButtonGuardarEmpleadoActionPerformed

    private void bttConsutaEdicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttConsutaEdicionActionPerformed
        // TODO add your handling code here:
        empleado = mdEmpleado.consultaEmpleadoId(jTextCodigoidEdicion.getText());
        
        if ( empleado != null){
            
            
            jTexNombreEditar.setText(empleado.getNombre());
            jTextApellidoEdit.setText(empleado.getApellido());
            jTextSalarioEdit.setText(String.valueOf(empleado.getSalario()));
            jTexHorasExtraEdit.setText(String.valueOf(empleado.getHorasExtra()));
        
            
            
        }else{
            JOptionPane.showMessageDialog(rootPane, "Empleado no Existe");
        }
        
        
        
        
        
    }//GEN-LAST:event_bttConsutaEdicionActionPerformed

    private void jButtoGuardarCambiosEdicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtoGuardarCambiosEdicionActionPerformed
        // TODO add your handling code here:
        
        
        try {
            if (jTexNombreEditar.getText().equals("") || jTextApellidoEdit.getText().equals("") || (Integer.valueOf(jTextSalarioEdit.getText()) <= 0)) {
                System.out.println("Nombre:  "+jTexNombreEditar.getText()+" apellido "+jTextApellidoEdit.getText()+ "  "+Integer.valueOf(jTextSalarioEdit.getText()));
                JOptionPane.showMessageDialog(rootPane, "los Datos Nombre,Apellido,Salario , Son Obligatorios");

            } else {
                 System.out.println("Nombre:Else>>>>>><  "+jTexNombreEditar.getText()+" apellido "+jTextApellidoEdit.getText()+ "  "+Integer.valueOf(jTextSalarioEdit.getText()));       
                if (mdEmpleado.editarEmpleado(Integer.valueOf(jTextCodigoidEdicion.getText()),jTexNombreEditar.getText(), Integer.valueOf(jTexHorasExtraEdit.getText()), jCheckBoxAuxilioTransporteEdit.isSelected(), Integer.valueOf(jTextSalarioEdit.getText()), jTextApellidoEdit.getText())) {
                    
                    JOptionPane.showMessageDialog(rootPane, "Empleado Edito Correctamente\n" + jTexNombreEmpleado1.getText() + " " + jTextApellido.getText());

                    jTextCodigoid.setText("");
                    jTexNombreEditar.setText("");
                    jTextApellidoEdit.setText("");
                    jTextSalarioEdit.setText("0");
                    jTexHorasExtraEdit.setText("0");
                    
                    jCheckBoxAuxilioTransporteEdit.setSelected(false);
                    actVistaempleado();

                } else {
                    JOptionPane.showMessageDialog(rootPane, "No Edito Intente De nuevo\n" + jTexNombreEditar.getText() + " " + jTextApellidoEdit.getText());

                }
            }

           
        } catch (Exception e) {
             JOptionPane.showMessageDialog(rootPane, "Error: \n Error Salario y Horas Extras Son Datos Numericos ");
            //(String nombre,int horasExtra,boolean AuxilioTransp,int salario,String apellido) 
        }
        
        
        
        
    }//GEN-LAST:event_jButtoGuardarCambiosEdicionActionPerformed

    private void jTexHorasExtraEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTexHorasExtraEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTexHorasExtraEditActionPerformed

    private void jButEliminarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButEliminarEmpleadoActionPerformed
        // TODO add your handling code here:
     
      
       int confir = JOptionPane.showConfirmDialog(rootPane, 
      "Esta Seguro que Desea Eliminar El Empleado Con Codigo: \n"+jTexCodigoEliminar.getText());
       
        System.out.println("confir:    "+confir);
        if(confir == JOptionPane.YES_OPTION){
            
            if(mdEmpleado.eliminarEmpleado(jTexCodigoEliminar.getText())){
                JOptionPane.showMessageDialog(rootPane, "Empleado Eliminado Correctamente");
                jTexCodigoEliminar.setText("");
                actVistaempleado();
            }else{
                 JOptionPane.showMessageDialog(rootPane, "Empleado No Existe");
            }
        }else{
            if(confir == JOptionPane.NO_OPTION){
                JOptionPane.showMessageDialog(rootPane, "Empleado No Eliminado");
            }
        }
        
    }//GEN-LAST:event_jButEliminarEmpleadoActionPerformed

    private void jButtonProsesoMasivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProsesoMasivoActionPerformed
        // TODO add your handling code here:
        
        
        LinkedList<Empleado> empleadoLista = mdEmpleado.listaEmpleado();   
        HashMap<Integer,ArrayList>listaNominas = new HashMap<Integer,ArrayList>();
        listaNominas= liquidacion.procesoMasivoNominaPrestaciones(empleadoLista);
        
        if(empleadoLista == null || listaNominas == null){
            JOptionPane.showMessageDialog(rootPane, "No Existe Datos Para Procesar"); 
      
            
        }else{
            listaNominaPrestaciones(listaNominas);
        }
        
    }//GEN-LAST:event_jButtonProsesoMasivoActionPerformed

    
    
    private void listaNominaPrestaciones(HashMap<Integer,ArrayList> listaNominas){
        DefaultListModel model = new DefaultListModel();
        
        int index =0;
        
        for (ArrayList i : listaNominas.values()) {
            String data = " Id:     "+i.get(0)+"           Nombre: "+i.get(1)+"         Nomina:  "+i.get(2)+"  Prestaciones:  "+i.get(3) ;
            model.add(index, data);
            index++;
            
        }
        
        jList1NominaMasiva.setModel(model);
        
    }
    
    
    
 // Mostrar lista de empleados en la lista ;
    // este metodo sirve para visualizar una lista en la pantalla de swing 
    
    private void listaEmpleado(){
        DefaultListModel model = new DefaultListModel();
        
        int index =0;
        for (Empleado empleado : empleadoLista) {
            String data = (index-1)+")      Id: "+empleado.getId()+
                    "          Nombre Completo: "+empleado.getNombre()+
                    "                 Apellido:        "+empleado.getApellido();
            model.add(index, data);
            index ++;
        }
       jlistEmpleado.setModel(model);
    }
    
    private void actVistaempleado(){
        // ponemos esto aqui para que se actualice la tabla nominaMasiva para cuando agamos cambios 
        this.empleadoLista = mdEmpleado.listaEmpleado();
        this.listaEmpleado();
    }
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane TablepaneGroup;
    private javax.swing.JButton bttConsulEmpleado;
    private javax.swing.JButton bttConsutaEdicion;
    private javax.swing.JButton jButEliminarEmpleado;
    private javax.swing.JButton jButtoGuardarCambiosEdicion;
    private javax.swing.JButton jButtonGenerarNOMINA;
    private javax.swing.JButton jButtonGuardarEmpleado;
    private javax.swing.JButton jButtonProsesoMasivo;
    private javax.swing.JCheckBox jCheckBoxAuxilioTransporte;
    private javax.swing.JCheckBox jCheckBoxAuxilioTransporteEdit;
    private javax.swing.JCheckBox jCheckBoxAuxilioTransporteEmpleado;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLTotalNomina;
    private javax.swing.JLabel jLTotalPrestaciones;
    private javax.swing.JLabel jLabApellido;
    private javax.swing.JLabel jLabApellido1;
    private javax.swing.JLabel jLabApellido2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelHorasExtras;
    private javax.swing.JLabel jLabelHorasExtras1;
    private javax.swing.JLabel jLabelHorasExtras2;
    private javax.swing.JLabel jLabelInfoNomina;
    private javax.swing.JLabel jLabelInfoNomina1;
    private javax.swing.JLabel jLabelInfoNomina2;
    private javax.swing.JLabel jLabelSalario;
    private javax.swing.JLabel jLabelSalario1;
    private javax.swing.JLabel jLabelSalario2;
    private javax.swing.JList<String> jList1NominaMasiva;
    private javax.swing.JPanel jPaInfoEmpleado;
    private javax.swing.JPanel jPaInfoEmpleado1;
    private javax.swing.JPanel jPaInfoEmpleado2;
    private javax.swing.JPanel jPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPanelDatosSalario;
    private javax.swing.JPanel jPanelDatosSalario1;
    private javax.swing.JPanel jPanelDatosSalario2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTexCodigoEliminar;
    private javax.swing.JTextField jTexHorasExtraEdit;
    private javax.swing.JTextField jTexHorasExtras;
    private javax.swing.JTextField jTexHorasExtrasEmpleado1;
    private javax.swing.JTextField jTexNombre;
    private javax.swing.JTextField jTexNombreEditar;
    private javax.swing.JTextField jTexNombreEmpleado1;
    private javax.swing.JTextField jTexNomina;
    private javax.swing.JTextField jTextApellido;
    private javax.swing.JTextField jTextApellidoEdit;
    private javax.swing.JTextField jTextApellidoEmpleado1;
    private javax.swing.JTextField jTextCodigoid;
    private javax.swing.JTextField jTextCodigoidEdicion;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextSalario;
    private javax.swing.JTextField jTextSalario1;
    private javax.swing.JTextField jTextSalarioEdit;
    private javax.swing.JTextField jTextTotalPrestaciones;
    private javax.swing.JLabel jlabeCodigo;
    private javax.swing.JLabel jlabeCodigo1;
    private javax.swing.JList<String> jlistEmpleado;
    // End of variables declaration//GEN-END:variables
}
